FROM bellsoft/liberica-openjdk-alpine:17.0.7 as BuildProject
WORKDIR /app
COPY ./java ./src
RUN mkdir ./bin
RUN javac -sourcepath ./src -d out ./src/ru/geekbrains/hw1/Main/Main.java

FROM scratch as OutputFiles
COPY --from=BuildProject /app/out /bin